name: "baltransfer-network"

# Describe what the target network is/does.
description: "The network which will host my first blockchain"

# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
version: 2

# The client section used by GO SDK.
client:
  # Which organization does this application instance belong to? The value must be the name of an org
  organization: Org1
  logging:
    level: info

  # Global configuration for peer, event service and orderer timeouts
  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 3s
      registrationResponse: 3s
  orderer:
    timeout:
      connection: 3s
      response: 5s

  # Root of the MSP directories with keys and certs. The Membership Service Providers is component that aims to offer an abstraction of a membership operation architecture.
  cryptoconfig:
    path: "${GOPATH}/src/balance_transfer/network/crypto-config"

  # Some SDKs support pluggable KV stores, the properties under "credentialStore" are implementation specific
  credentialStore:
    path: "/tmp/balance_transfer-service-kvs"

     # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: "/tmp/balance_transfer-service-msp"

  # BCCSP config for the client. Used by GO SDK. It's the Blockchain Cryptographic Service Provider.
  # It offers the implementation of cryptographic standards and algorithms.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

  tlsCerts:
    systemCertPool: false

# [Optional]. But most apps would have this section so that channel objects can be constructed based on the content below.
# If one of your application is creating channels, you might not use this
channels:
  channel1:
    orderers:
      - orderer.hf.baltransfer.io

    # Network entity which maintains a ledger and runs chaincode containers in order to perform operations to the ledger. Peers are owned and maintained by members.
    peers:
      peer0.org1.hf.baltransfer.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org1.hf.baltransfer.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.hf.baltransfer.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org2.hf.baltransfer.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

# List of participating organizations in this network
organizations:
  Org1:
    mspid: org1.hf.baltransfer.io
    cryptoPath: "peerOrganizations/org1.hf.baltransfer.io/users/{userName}@org1.hf.baltransfer.io/msp"
    peers:
      - peer0.org1.hf.baltransfer.io
      - peer1.org1.hf.baltransfer.io
    certificateAuthorities:
      - ca.org1.hf.baltransfer.io
  Org2:
    mspid: org2.hf.baltransfer.io
    cryptoPath: "peerOrganizations/org2.hf.baltransfer.io/users/{userName}@org2.hf.baltransfer.io/msp"
    peers:
      - peer0.org2.hf.baltransfer.io
      - peer1.org2.hf.baltransfer.io
    certificateAuthorities:
      - ca.org2.hf.baltransfer.io

# List of orderers to send transaction and channel create/update requests to.
# The orderers consent on the order of transactions in a block to be committed to the ledger. For the time being only one orderer is needed.
orderers:
  orderer.hf.baltransfer.io:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.hf.baltransfer.io
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: "${GOPATH}/src/balance_transfer/network/crypto-config/ordererOrganizations/hf.baltransfer.io/tlsca/tlsca.hf.baltransfer.io-cert.pem"

# List of peers to send various requests to, including endorsement, query and event listener registration.
peers:
  peer0.org1.hf.baltransfer.io:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.org1.hf.baltransfer.io
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/balance_transfer/network/crypto-config/peerOrganizations/org1.hf.baltransfer.io/tlsca/tlsca.org1.hf.baltransfer.io-cert.pem"

  peer1.org1.hf.baltransfer.io:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer1.org1.hf.baltransfer.io
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      # Certificate location absolute path
      path: "${GOPATH}/src/balance_transfer/network/crypto-config/peerOrganizations/org1.hf.baltransfer.io/tlsca/tlsca.org1.hf.baltransfer.io-cert.pem"

  peer0.org2.hf.baltransfer.io:
    url: grpcs://localhost:7151
    eventUrl: grpcs://localhost:7153
    grpcOptions:
      ssl-target-name-override: peer0.org2.hf.baltransfer.io
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      # Certificate location absolute path
      path: "${GOPATH}/src/balance_transfer/network/crypto-config/peerOrganizations/org2.hf.baltransfer.io/tlsca/tlsca.org2.hf.baltransfer.io-cert.pem"

  peer1.org2.hf.baltransfer.io:
    url: grpcs://localhost:8151
    eventUrl: grpcs://localhost:8153
    grpcOptions:
      ssl-target-name-override: peer1.org2.hf.baltransfer.io
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      # Certificate location absolute path
      path: "${GOPATH}/src/balance_transfer/network/crypto-config/peerOrganizations/org2.hf.baltransfer.io/tlsca/tlsca.org2.hf.baltransfer.io-cert.pem"



# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows certificate management to be done via REST APIs.
certificateAuthorities:
  ca.org1.hf.baltransfer.io:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.hf.baltransfer.io

certificateAuthorities:
  ca.org2.hf.baltransfer.io:
    url: https://localhost:7058
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org2.hf.baltransfer.io
